// GENERATED by scratchpad/build_cfs_fonts.py from the retail uiart CFS fonts - do not edit by hand.
// Glyph i = ASCII 32+i. glyphs[i] = [bearing, width] inside a cell x cell box; the sheet holds glyph i at x = i*cell.
// Rendering rules (studio skinAssets.ts, binary-exact): advance = width + 1; the pen ignores the bearing;
// a blank glyph (space) advances cell/2; unknown characters use glyph 0.

export interface CfsFont {
  name: string;
  cell: number;
  sheet1x: string;
  sheet2x: string;
  glyphs: Array<[number, number]>;
}

export const FONT_SMALL: CfsFont = {
  name: 'small',
  cell: 8,
  sheet1x: '/ui-fonts/font-small.png',
  sheet2x: '/ui-fonts/font-small@2x.png',
  glyphs: [[0,0],[3,2],[1,6],[0,7],[1,6],[0,7],[0,7],[3,2],[2,4],[2,4],[1,7],[1,6],[2,4],[1,6],[3,3],[2,5],[1,6],[1,6],[1,6],[1,6],[1,7],[1,6],[1,6],[1,6],[1,6],[1,6],[2,3],[1,4],[1,5],[1,6],[2,5],[1,6],[0,7],[0,8],[1,6],[1,6],[1,7],[1,6],[1,6],[1,6],[1,6],[2,4],[1,6],[1,6],[1,6],[1,7],[1,7],[1,6],[1,6],[1,7],[1,6],[1,6],[1,6],[1,6],[1,7],[1,7],[1,6],[1,6],[1,6],[2,4],[1,5],[2,4],[0,7],[0,8],[2,4],[1,6],[1,6],[1,6],[1,6],[1,6],[1,6],[1,6],[1,6],[1,6],[1,5],[1,6],[1,6],[1,7],[1,6],[1,6],[1,6],[1,6],[1,6],[1,6],[1,6],[1,6],[1,6],[1,7],[1,6],[1,6],[1,6],[2,4],[3,2],[2,4],[0,7]],
};

export const FONT_MEDIUM: CfsFont = {
  name: 'medium',
  cell: 12,
  sheet1x: '/ui-fonts/font-medium.png',
  sheet2x: '/ui-fonts/font-medium@2x.png',
  glyphs: [[0,0],[1,2],[1,6],[0,9],[0,8],[0,10],[0,11],[2,2],[3,5],[1,5],[1,9],[1,5],[3,2],[2,5],[1,2],[0,6],[0,8],[0,6],[0,8],[0,8],[0,9],[0,8],[0,8],[0,8],[0,8],[0,8],[1,2],[1,3],[1,5],[0,7],[1,5],[1,7],[0,11],[0,11],[0,9],[0,10],[0,10],[0,7],[0,7],[0,10],[0,9],[2,6],[1,8],[1,8],[1,7],[1,11],[1,9],[1,10],[1,8],[1,10],[1,8],[1,9],[1,8],[1,9],[1,10],[0,11],[0,11],[0,10],[0,8],[1,4],[1,6],[1,4],[1,7],[0,8],[1,2],[1,7],[1,8],[1,8],[1,8],[1,8],[1,5],[1,8],[1,8],[1,2],[1,3],[1,8],[1,2],[1,10],[1,8],[1,8],[1,8],[1,8],[1,7],[1,7],[1,5],[1,7],[1,7],[1,9],[1,7],[1,8],[0,7],[1,4],[2,1],[1,4],[1,9]],
};
